kernel:
  resource: ../../src/Kernel.php
  type: annotation

user_controllers:
  resource: ../../src/Adapter/Framework/Http/Controller/User/
  type: annotation
  prefix: /api/users
  trailing_slash_on_root: false

#Company_controllers:
#  resource: ../../src/Adapter/Framework/Http/Controller/Company/
#  type: annotation
#  prefix: /api/Companys
#  trailing_slash_on_root: false