kernel:
  resource: ../../src/Kernel.php
  type: annotation

user_controllers:
  resource: ../../src/Adapter/Framework/Http/Controller/User/
  type: annotation
  prefix: /api/v1/userss
  trailing_slash_on_root: false

#Company_controllers:
#  resource: ../../src/Adapter/Framework/Http/Controller/Company/
#  type: annotation
#  prefix: /api/v1/companiess
#  trailing_slash_on_root: false