controllers:
    resource:
        path: ../src/Adapter/Framework/Http/Controller/
        namespace: App\Adapter\Framework\Http\Controller
    type: attribute

# config/routes.yaml
api_login_check:
    path: /api/login_check