on:
  pull_request:
    branches:
      - main

jobs:
  app_checks:
    name: App Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull docker-compose
        run: docker-compose -f docker-compose.yml.dist pull

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Prepare containers
        run: 
          make start 
          make composer-install

      - name: buffering time for db container
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Create test database
        run: make test-setup-db
        
      - name: Run tests
        run: make tests
