on:
  pull_request:
    branches:
      - main

jobs:
  app_checks:
    name: App Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Pull docker-compose
        run: docker-compose -f docker-compose.yml.dist pull

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Prepare containers
        run: 
          docker network create cch-network || true
          cp -n docker-compose.yml.dist docker-compose.yml || true
          U_ID=${UID} docker-compose up -d 
          U_ID=${UID} docker exec --user ${UID} ${DOCKER_BE} composer install --no-interaction

      - name: Wait for database
        run: sleep 10

      - name: Create test database
        run: 
          U_ID=${UID} docker exec -it --user ${UID} ${DOCKER_BE} php bin/console doctrine:database:create --if-not-exists --env=test 
          U_ID=${UID} docker exec -it --user ${UID} ${DOCKER_BE} php bin/console doctrine:schema:update --force --env=test

      - name: Run tests
        run: U_ID=${UID} docker exec --user ${UID} ${DOCKER_BE} vendor/bin/phpunit -c phpunit.xml.dist
