
on:
  pull_request:
    branches:
      - main

jobs:
  app_checks:
    name: App Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Pull docker-compose
        run: cp -n docker-compose.yml.dist docker-compose.yml && docker-compose -f docker-compose.yml pull

      - uses: satackey/action-docker-layer-caching@latest
        continue-on-error: true

      - name: Prepare containers
        run: make start && make composer-install

      - name: buffering time for db container
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Generate JWT Keys
        run: docker exec --user $(id -u) cch-app php bin/console lexik:jwt:generate-keypair --overwrite

      - name: Create test DB
        run: |
          docker exec --user $(id -u) cch-app php bin/console doctrine:database:create --if-not-exists --env=test
          docker exec --user $(id -u) cch-app php bin/console doctrine:schema:update --force --env=test

      - name: Run tests
        run: make tests
