name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  app_checks:
    name: App Checks
    runs-on: ubuntu-latest
    env:
      DOCKER_BE: cch-app
      U_ID: 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Docker network
        run: docker network create cch-network || true

      - name: Copy docker-compose config
        run: cp -n docker-compose.yml.dist docker-compose.yml || true

      - name: Start containers
        run: docker-compose up -d

      - name: Install dependencies
        run: docker exec --user ${U_ID} ${DOCKER_BE} composer install --no-interaction

      - name: Run coding style check
        run: docker exec --user ${U_ID} ${DOCKER_BE} vendor/bin/php-cs-fixer fix --dry-run

      - name: Wait for database
        run: sleep 10

      - name: Setup test database
        run: |
          docker exec --user ${U_ID} ${DOCKER_BE} php bin/console doctrine:database:create --if-not-exists --env=test
          docker exec --user ${U_ID} ${DOCKER_BE} php bin/console doctrine:schema:update --force --env=test

      - name: Run tests
        run: docker exec --user ${U_ID} ${DOCKER_BE} vendor/bin/phpunit -c phpunit.xml.dist
